### ISSUE TITLE
Pull Request to cakeslice?

### ISSUE THREAD

**Issue by hybridherbst** [JimmyCushnie/Outline-Effect-but-its-faster#3]
Is there a reason why this hasn't been PR'ed into cakeslices original repo? Seems like it would be great to get the two back on par to improve work on both - I'd like to add LWRP/HDRP support but unsure whether to start from cakeslice or from this fork.

**Comment by JimmyCushnie** [comment]
There are two reasons I haven't PR'd to cakeslice:

1. There are several months-old PRs that cakeslice hasn't even commented on. They don't seem to be actively maintaining the original repo. One of the reasons I made this fork, actually, was so that I could merge all those PRs.

2. I have totally restructured this project. cakeslice is a repo for an entire Unity project, this repo is for just the outline stuff. It's generally frowned upon to make a PR that changes things like this, that should be up to the maintainer.

If cakeslice becomes active again, I'll message them and ask whether they want me to PR. But since this would be a very unconventional PR and they don't seem to be looking at PRs anyway, I don't really see the point.

Sidenote about SRP: since switching my project to LWRP, I've switched from Outline Effect to [PRO Outline](https://assetstore.unity.com/packages/vfx/shaders/fullscreen-camera-effects/pro-outline-136956). Perhaps you'd want to look into that. I wish the author would make it open source so I could put my fork of it on github, but oh well.

**Comment by hybridherbst** [comment]
Thanks for your reply. I saw that you were doing all those merges, good job. Maybe you could just merge the latest two changes from cakeslice that are not in your repo yet?

Thanks for the link with PRO Outline: I saw that too and it looks cool. Just wanted to ask here first - so good to know what the status is!

**Comment by JimmyCushnie** [comment]
> Maybe you could just merge the latest two changes from cakeslice that are not in your repo yet?

I'd like to, but merging from cakeslice is tricky as I've made a ton of changes to both the project organization and the files themselves. If someone makes a PR for it I'd be happy to merge, but frankly I'm just too busy with other things to do it myself.

**Comment by cakeslice** [comment]
Hello! I didn't know this existed, great work! 

I've been very very busy and don't have time to develop the Outline Effect anymore, only on rare occasions.

You can PR, I will accept all the changes since they make sense :)

**Comment by JimmyCushnie** [comment]
Thank you @cakeslice , glad to see you're back!

[The PR has been made.](https://github.com/cakeslice/Outline-Effect/pull/43)
